name: Global workflow to rule them all

on:
  push:
      branches: [ master ] #or main

jobs:

  replicate_changes:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Replicating global workflow
          uses: derberg/copy-files-to-other-repositories@v1.0.0
          with:
            github_token: ${{ secrets.CUSTOM_TOKEN }}
            patterns_to_ignore: '.github/workflows/name_of_file_where_this_action_is_used.yml'
            patterns_to_include: '.github/workflows'
            repos_to_ignore: repo1,repo2
            topics_to_include: topic1,topic2
            exclude_private: true
            exclude_forked: true
            branches: .*-release,main
            committer_username: santiago-bernabeu
            committer_email: my-email@me.com
            commit_message: "ci: update global workflows"
            
workflow_dispatch:
    inputs:
      repo_name: fartcoin-project
        description: |
          You can specify name of the repository where workflows should be pushed manually. As long as repository is not ignored by workflow settings.
          If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
        required: false
