name: REAME update

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'README.md'
  workflow_dispatch:
    inputs:
      repo_name:
        description: |
          You can specify name of the repository where workflows should be pushed manually. As long as repository is not ignored by workflow settings.
          If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
        required: false

jobs:
  replicate_contributing:
      name: Replicate README guide to all repositories
      runs-on: PoloniexTradeBot
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replicating file
        uses: derberg/copy-files-to-other-repositories@v1.0.0
        with:
          github_token: ${{ secrets.SECRETS }}
          patterns_to_include: README.md
          repos_to_ignore: Calculate_FART_Mining_Reward,brute_force38,fartcoin,MiningPool,BlockExplorer,Block-EXE-Firewall,VLC-mobile-remote
          committer_username: fartcoin-project
          committer_email: fartcoin-project@gmail.com
          commit_message: "ci: update global readme guide"
